name: bazel-container
description: setup minimal container for bazel build env
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: install g++12
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y g++-12
        sudo rm -f /usr/bin/g++
        sudo ln -s /usr/bin/g++-12 /usr/bin/g++
    - name: install autotools
      shell: bash
      run: |
        sudo apt update
        sudo apt install autoconf autotools-dev
    - name: install bazel ${{ env.USE_BAZEL_VERSION }}
      if: ${{ env.ACT }}
      shell: bash
      run: npm install -g @bazel/bazelisk
    - uses: bazelbuild/setup-bazelisk@v2
      if: ${{ !env.ACT }}
    - name: setup bazel cache
      if: ${{ !env.ACT }}
      uses: actions/cache@v3
      with:
        path: "~/.cache/bazel"
        key: bazel